### ISSUE TITLE
Broken since last update

### ISSUE THREAD

**Issue by Traderain** [erdomke/RtfPipe#10]
Since the last update no matter what I do I get an error:
```
System.InvalidOperationException: 'Stack empty.'
```
My code:
```csharp
            using (var reader = new StringReader(Resources.wcc_eula))
            {
                browserwcclicense.DocumentText = Rtf.ToHtml(reader);
            }
```

**Comment by erdomke** [comment]
Can you provide me with a sample RTF document that is causing the issue?

**Comment by richardsummers2019** [comment]
This rtf will generate the error:

{\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fnil\fcharset0 MS Sans Serif;}}
\viewkind4\uc1\pard\lang2057\f0\fs16\line Error can be found using this\par
}
