### ISSUE TITLE
RtfPipe.Converter.Text.RtfTextConverter

### ISSUE THREAD

**Issue by 4g0st1n0** [erdomke/RtfPipe#12]
I'm using RtfPipe.Converter.Text.RtfTextConverter to convert rtf to plainText 

With latest release Converters are removed. How can convert Rtf to plain text?

Thank you.

**Comment by erdomke** [comment]
The `Rtf.ToHtml` method has an overload where you can pass in an `XmlWriter` to which the HTML is written.  This leaves you with a couple of options:

1. A separate open source project of mine, [BracketPipe](https://github.com/erdomke/BracketPipe), contains `XmlWriter` classes designed to convert html to [Markdown](https://github.com/erdomke/BracketPipe/blob/master/src/BracketPipe/Parser/Text/MarkdownWriter.cs), [Textile](https://github.com/erdomke/BracketPipe/blob/master/src/BracketPipe/Parser/Text/TextileWriter.cs), and ["plain text"](https://github.com/erdomke/BracketPipe/blob/master/src/BracketPipe/Parser/Text/PlainTextWriter.cs). (The Markdown writer should be more complete while the Textile writer has a few remaining issues.) Therefore, your code might look something like:

```csharp
using (var writer = new System.IO.StringWriter())
using (var markdown = new BracketPipe.MarkdownWriter(writer))
{
  Rtf.ToHtml(source, markdown);
  markdown.Flush();
  return writer.ToString();
}
```

2. Create your own subclass of `XmlWriter` and use code similar to above.  In general, any calls to `WriteString` that are not between calls to `WriteStartAttribute` and `WriteEndAttribute` should contain the plain text content of the HTML (and therefore, RTF).  If you need to perform additional formatting (e.g. separating paragraphs with newlines), you can use the `WriteStartElement` and `WriteEndElement` to listen for `<br>` and `<p>` tags.  Again the [`PlainTextWriter`](https://github.com/erdomke/BracketPipe/blob/master/src/BracketPipe/Parser/Text/PlainTextWriter.cs) code gives you a decent example (even if perhaps a touch complicated) of what this might look like.
