### ISSUE TITLE
Why is RtfPipe-Signed not updated on NuGet?

### ISSUE THREAD

**Issue by SaphuA** [erdomke/RtfPipe#13]
https://www.nuget.org/packages/RtfPipe/

Version | Downloads | Last updated
-- | -- | --
1.0.0.23 | 948 | 2 months ago

https://www.nuget.org/packages/RtfPipe-Signed/

Version | Downloads | Last updated
-- | -- | --
0.7.0.3 | 1.151 | 12-4-2017

**Comment by SaphuA** [comment]
Oh I see now the signed version was created by someone else.

**Comment by Sicos1977** [comment]
Please make a signed version... I have a strong typed project that needs it :-)

**Comment by erdomke** [comment]
I don't have the bandwidth to manage signing this package currently. If there is enough interest, I can re-evaluate in the future.

**Comment by Sicos1977** [comment]
Signing a package is just 10 seconds work
