### ISSUE TITLE
Incorrect coding of unicode char with trailing space

### ISSUE THREAD

**Issue by HakanL** [erdomke/RtfPipe#14]
I have this RTF snippet:
`{\f3\cf0 Kartl\u228\'e4gga hur }{\b\f3\cf0 medarbetarna}{\f3\cf0  upplever sin h\u228\'e4lsa, arbetsmilj\u246\'f6 och livsstil.}\f3`

and it should basically look like this:

> Kartlägga hur **medarbetarna** upplever sin hälsa, arbetsmiljö och livsstil.

but when I parse this using RtfPipe I get a TextToken that has the text like this:

> upplever sin hälsa, arbetsmiljöoch livsstil.

Note how it's missing a space here "arbetsmiljöoch". It's where the \u246 part is in the RTF, seems like there's an issue in how RtfPipe is interpreting this. If I open this in MS Word is looks korrekt.

**Comment by erdomke** [comment]
This should be fixed in the latest release.
