### ISSUE TITLE
Unicode placeholders failing

### ISSUE THREAD

**Issue by broderickhyman** [erdomke/RtfPipe#18]
Rtf for a [Smiling Face](https://www.fileformat.info/info/unicode/char/1f60a/index.htm): \u-10179 ?\u-8694 ?
This will currently convert to: \ud83d?\ude0a?
Needs to convert to: 😊
Seems to be that in this case it is failing to consider the ? to be part of the unicode word.
I already have an initial fix and will submit a PR.

**Comment by erdomke** [comment]
This should be fixed in the latest release.
