### ISSUE TITLE
Font name parse wrong.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [erdomke/RtfPipe#20]
I'm Chinese user. I use RtfPipe convert rtf to html, but Chinese fontname parse failed.
I try to debug it, find this token's encoding is wrong.
this is wrong, because `StringBuffer`'s charset is not correct:
![default](https://user-images.githubusercontent.com/10345361/50418122-d5e7c980-0864-11e9-94a5-0831d57264b1.png)
this is ok:
![default](https://user-images.githubusercontent.com/10345361/50418416-31668700-0866-11e9-89da-cfa59778fa60.png)

**Comment by MiyamuraMiyako** [comment]
I find 
![default](https://user-images.githubusercontent.com/10345361/50431654-6b3b9a00-0907-11e9-8083-e1beca61bb1b.png)
this method using `Encoding.GetString` method.
May be shoud use `Encoding.Default.GetString` ?

**Comment by MiyamuraMiyako** [comment]
I created new pull request.

**Comment by erdomke** [comment]
A more robust fix for this is now included in the source.
