### ISSUE TITLE
Rtf insert Word(doc) convert to html format not accurate enough

### ISSUE THREAD

**Issue by MiyamuraMiyako** [erdomke/RtfPipe#23]
Rtf insert Word(doc) convert to html format not accurate enough

**Comment by erdomke** [comment]
Can you provide a sample rtf document that isn't converting properly and describe where the defects are? Thanks!

**Comment by MiyamuraMiyako** [comment]
@erdomke ok，I upload one.
[201809121900660003339549.zip](https://github.com/erdomke/RtfPipe/files/2791357/201809121900660003339549.zip)

**Comment by erdomke** [comment]
This should be improved in the latest release.

**Comment by MiyamuraMiyako** [comment]
@erdomke  Some formatting errors were fixed, but there are still some inaccuracies. may be have more improve space?
![default](https://user-images.githubusercontent.com/10345361/52529639-3c02b000-2d30-11e9-9d89-6667034213d2.png)
![default](https://user-images.githubusercontent.com/10345361/52529633-1fff0e80-2d30-11e9-90b0-a8a310f11f82.png)
