### ISSUE TITLE
Web links

### ISSUE THREAD

**Issue by K-Flynn** [erdomke/RtfPipe#32]
VS2019
All updates etc etc
Latest RtFPipe

Save a document in a rich text box with 

"address@hotmail.co.uk" I get a perfectly formed html document & hyperlink when sent by email (MailKit)

"http://www.anything.com" or "https://anything.com" doesn't format as a hyperlink in the onverted string.

rtf displays correctly as a hyperlink and reads....

{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}}
{\colortbl ;\red0\green0\blue255;\red0\green0\blue0;}
{\*\generator Riched20 10.0.18362}\viewkind4\uc1 
\pard {\f0\fs17{\field{\*\fldinst{HYPERLINK http://www.xxxx.co.uk }}{\fldrslt{http://www.xxxx.co.uk\ul0\cf0}}}}\cf2\f0\fs17\par
\par
\par

However the converted html when sent as an email displays the text but doesn't recognise the hyperlink...

"<div style=""font-size:12pt;font-family:&quot;Microsoft Sans Serif&quot;;""><p style=""font-size:8.5pt;margin:0;""><a style=""text-decoration:none;"">http://www.xxxx.co.uk</a></p><p style=""font-size:8.5pt;margin:0;""><br></p><p style=""font-size:8.5pt;margin:0;""><br></p><p style=""font-size:8.5pt;margin:0;"">

Suggestions?

**Comment by K-Flynn** [comment]
![1](https://user-images.githubusercontent.com/38295905/64653691-fa99c680-d41e-11e9-98f0-883813d20944.PNG)
![2](https://user-images.githubusercontent.com/38295905/64653709-17ce9500-d41f-11e9-9417-d67d53e8874a.PNG)

**Comment by K-Flynn** [comment]
![3](https://user-images.githubusercontent.com/38295905/64653823-5b290380-d41f-11e9-8bd2-623cc8ac98be.PNG)

**Comment by erdomke** [comment]
Version 1.0.7232.28557 is being pushed to NuGet now which should address some problems that I discovered when debugging this issue. However, the RTF you posted is not valid. The correct syntax should be (note that the `*` should be preceded by a `\` producing the symbol `\*`). While the new package will correctly handle the valid syntax, I am not sure what to recommend if you are truly getting invalid RTF.

```rtf
{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}}
{\colortbl ;\red0\green0\blue255;\red0\green0\blue0;}
{\*\generator Riched20 10.0.18362}\viewkind4\uc1
\pard {\f0\fs17{\field{\*\fldinst{HYPERLINK http://www.xxxx.co.uk }}{\fldrslt{http://www.xxxx.co.uk\ul0\cf0}}}}\cf2\f0\fs17\par
\par
\par
```
