### ISSUE TITLE
Issue handling table row and column?

### ISSUE THREAD

**Issue by ThisNoName** [erdomke/RtfPipe#35]
I have a Rtf with a table of mixed columns.  It appears the converter couldn't handle it and put colspan at the wrong place.

There are other[ code sample like the one by Mathew on MSDN](https://code.msdn.microsoft.com/windowsdesktop/Converting-between-RTF-and-aaa02a6e/view/SourceCode) that seems recognize the scenario and split the table into two.  

I wonder if such mixed column is not covered by the library, or a bug.  Thanks.

Rtf View (Original table doesn't have border on title 2, turned on for screenshot)
![SourceRtf](https://user-images.githubusercontent.com/5599527/68035201-8d294a00-fc99-11e9-9ec4-6d05a1fca2dd.jpg)

Result Html
![TargetHtml](https://user-images.githubusercontent.com/5599527/68033774-c44a2c00-fc96-11e9-80da-3243c5814bc9.jpg)

RTF source
`{\rtf1\sstern21000\ansi\deflang1033\ftnbj\uc1\deff0
{\fonttbl{\f0 \fmodern \fcharset0 Courier New;}{\f1 \fnil Courier New;}{\f2 \fswiss \fcharset0 Arial;}{\f3 \froman \fcharset2 Symbol;}{\f4 \fnil \fcharset0 Segoe UI;}{\f5 \fnil \fcharset0 Arial;}}
{\colortbl ;\red255\green255\blue255 ;\red0\green0\blue0 ;\red255\green0\blue0 ;\red0\green112\blue192 ;\red0\green176\blue80 ;\red112\green48\blue160 ;\red255\green131\blue0 ;\red0\green255\blue0 ;\red187\green49\blue185 ;\red0\green176\blue240 ;\red255\green0\blue255 
;\red24\green232\blue208 ;\red255\green105\blue180 ;\red153\green102\blue255 ;\red0\green0\blue0 ;\red128\green128\blue128 ;}
{\stylesheet{\f1\fs10\b0\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf0\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 Normal;}{\cs1\f0\fs0\b0\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf0\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 
Default Paragraph Font;}{\cs2\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf3\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 Style0;}{\cs3\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf4\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 
Style1;}{\cs4\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf5\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 Style2;}{\cs5\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf6\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 
Style3;}{\cs6\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf7\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 Style4;}{\cs7\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf8\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 
Style5;}{\cs8\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf9\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 Style6;}{\cs9\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf10\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 
Style7;}{\cs10\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf11\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 Style8;}{\cs11\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf12\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 
Style9;}{\cs12\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf13\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 Style10;}{\cs13\f0\fs28\b\ul0\uldb0\uld0\embo0\i0\v0\strike0\striked0\protect0\super0\sub0\sshlink0\caps0\scaps0\cf14\cb1\chcbpat1\ulc0\expnd0\expndtw0\charscalex100\dn0 
Style11;}}
{\*\revtbl{Unknown;}}
\paperw12240\paperh15840\margl1800\margr1800\margt1440\margb1440\headery720\footery720\nogrowautofit\deftab720\formshade\nofeaturethrottle1\dntblnsbdb\fet4\aendnotes\aftnnrlc\pgbrdrhead\pgbrdrfoot
\sectd\pgwsxn12240\pghsxn15840\guttersxn0\marglsxn1800\margrsxn1800\margtsxn1440\margbsxn1440\headery720\footery720\sbkpage\pgncont\pgndec
\plain\plain\f1\fs10\pard\plain\f1\fs10
{\*\bkmkstart bk9000502441403060}{\*\bkmkend bk9000502441403060}\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20\b\ul Test Title:\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20  \par
\trowd\trgaph10\trpaddl10\trpaddfl3\trpaddr10\trpaddfr3\trpaddt0\trpaddft3\trpaddb0\trpaddfb3\trleft0
\clvertalt\clpadt10\clpadft3\clpadr10\clpadfr3\cellx3824
\clvertalt\clpadt10\clpadft3\clpadr10\clpadfr3\cellx8640
\pard\intbl\ssparaaux0\s0\fi-120\li120\ql\plain\f1\fs10{\*\bkmkstart bk9000502446403060}{\*\bkmkend bk9000502446403060}\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20\b Test Title Two\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20\cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20\cell
\intbl\row
\trowd\trgaph0\trpaddl48\trpaddfl3\trpaddr48\trpaddfr3\trpaddt48\trpaddft3\trpaddb48\trpaddfb3\trleft0
\clvertalt\clbrdrt\brdrs\brdrw20\brdrcf16\clbrdrb\brdrs\brdrw20\brdrcf16\clbrdrl\brdrs\brdrw20\brdrcf16\clbrdrr\brdrs\brdrw20\brdrcf16\clpadt48\clpadft3\clpadr48\clpadfr3\clpadl48\clpadfl3\clpadb48\clpadfb3\cellx2374
\clvertalt\clbrdrt\brdrs\brdrw20\brdrcf16\clbrdrb\brdrs\brdrw20\brdrcf16\clbrdrl\brdrs\brdrw20\brdrcf16\clbrdrr\brdrs\brdrw20\brdrcf16\clpadt48\clpadft3\clpadr48\clpadfr3\clpadl48\clpadfl3\clpadb48\clpadfb3\cellx5507
\clvertalt\clbrdrt\brdrs\brdrw20\brdrcf16\clbrdrb\brdrs\brdrw20\brdrcf16\clbrdrl\brdrs\brdrw20\brdrcf16\clbrdrr\brdrs\brdrw20\brdrcf16\clpadt48\clpadft3\clpadr48\clpadfr3\clpadl48\clpadfl3\clpadb48\clpadfb3\cellx8640
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20\cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20\b                       RIGHT\cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20\b                       LEFT\cell
\plain\f2\fs20\lang1033\hich\f2\dbch\f2\loch\f2\fs20\intbl\row
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16\b Visual\cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16 N/A \cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16 N/A\cell
\intbl\row
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16\b Motility\cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16 N/A \cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16 N/A\cell
\intbl\row
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16\b Other\cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16   \cell
\pard\intbl\ssparaaux0\s0\ql\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16  \cell
\intbl\row
\pard\plain\f1\fs10\plain\f5\fs16\lang1033\hich\f5\dbch\f5\loch\f5\fs16\par
\plain\f2\fs10\lang1033\hich\f2\dbch\f2\loch\f2\fs10\par
}
`

**Comment by erdomke** [comment]
This is fixed in the latest package.

**Comment by ThisNoName** [comment]
Works great!  Thank you so much the quick update!
