### ISSUE TITLE
Text alignment is broken starting from version 1.0.x

### ISSUE THREAD

**Issue by michaelantoun** [erdomke/RtfPipe#38]
Text alignment was working fine until v0.7.0.6. After upgrading to version 1.0.x, text is always aligned to the left. I also tried with the latest version 1.0.7322.27725 but with no luck.

**RTF input**:
`{\rtf1\ansi\ansicpg1252\uc1\htmautsp\deff2{\fonttbl{\f0\fcharset0 Times New Roman;}{\f2\fcharset0 Segoe UI;}{\f3\fcharset0 Arial;}}{\colortbl\red0\green0\blue0;\red255\green255\blue255;}\loch\hich\dbch\pard\plain\ltrpar\itap0{\lang1033\fs20\f3\cf0 \cf0\ql{\f3 {\ltrch Left}\li0\ri0\sa160\sb0\fi0\ql\par}
{\f3 {\ltrch Center}\li0\ri0\sa160\sb0\fi0\qc\par}
{\f3 {\ltrch Right}\li0\ri0\sa160\sb0\fi0\qr\par}
}
}`

**Here is the generated HTML**:
`<div style="font-size:12pt;font-family:&quot;Segoe UI&quot;;"><p style="font-size:10pt;text-align:left;font-family:Arial;margin:0;">Left</p><p style="font-size:10pt;text-align:left;font-family:Arial;margin:0;">Center</p><p style="font-size:10pt;text-align:left;font-family:Arial;margin:0;">Right</p></div>`

Thanks!

**Comment by erdomke** [comment]
This should now be resolved after the latest release.
