### ISSUE TITLE
Underline is converted shorter than original length

### ISSUE THREAD

**Issue by RobertoLuongo** [erdomke/RtfPipe#42]
Hi,

I am converting the rtf below using the latest stable version of RtfPipe: 1.0.7388.1242, 

[OverviewPolicyClaims-RTF.txt](https://github.com/erdomke/RtfPipe/files/4827805/OverviewPolicyClaims-RTF.txt)
which is basically a text with an underline below

The issue I am facing is that the underline underneath the text in the converted html file below is not of the same length of the original rtf, is actually 163px shorter

[OverviewPolicyClaims-HTML.txt](https://github.com/erdomke/RtfPipe/files/4827837/OverviewPolicyClaims-HTML.txt)

underline in rtf is : 960px
underline in converted html is : 796.81px 
see picture below
![ShorterUnderline-OverviewPolicyClaims](https://user-images.githubusercontent.com/20645085/85713597-6f559d00-b6e1-11ea-9b0e-4cf96b570932.jpg)

Any ideas why this is happening ?

thanks in advance

**Comment by erdomke** [comment]
Unfortunately, I haven't had a chance to look at this (or the other issue) yet due to being busy the last several days. Hopefully I will have some extra time this weekend.

**Comment by erdomke** [comment]
So I looked into this, and I can't replicate the exact problem you are describing. The attached RTF file renders in MS Word with 250 spaces of size 12pt Arial font. The HTML rendering has 249 spaces of size 12pt Arial font which renders as 1108.05px in Firefox 77. As far as I can tell, the only bug is that the space count is off by 1, but it should not be causing the magnitude of the discrepancy you are seeing.
