### ISSUE TITLE
Handling caharcters

### ISSUE THREAD

**Issue by goroggy** [erdomke/RtfPipe#45]
Eric, these are two hack fixes that you may find useful or not. 
Admittedly they stem from earlier versions.
Thanks.
 try
                    {
                        html = RtfPipe.Rtf.ToHtml(rtf);
                    }
                    catch ( Exception ex )
                    {
                        if ( ex.Message.Contains("undefined color index") )
                        {
                            string color = ex.Message.Split(':').Last().Trim();
                            rtf = rtf.Replace(@"\cf" + color, @"\cf0");
                        }
                        else if ( ex.Message.Contains("is an invalid character") )
                        {
                            string hex =
                                Regex.Match(ex.Message, @"hexadecimal value (.*?),").Groups[1].Value.Split('x')[1];
                            string dec = int.Parse(hex, NumberStyles.HexNumber).ToString().PadLeft(4, '0');
                            rtf = rtf.Replace(@"\u" + dec, "");
                        }

**Comment by erdomke** [comment]
Thanks for the suggestion. Unfortunately, I don't think those errors apply to the current version. If you are running into issues parsing RTF, please post an example and I can look into what might need to change with the library.
