### ISSUE TITLE
Encoding for "Windows-1252" not working in .NET Core

### ISSUE THREAD

**Issue by stefansolid** [erdomke/RtfPipe#5]
In a ASP.NET Core application the encoding for windows was not found, the line below failed:

public static readonly Encoding AnsiEncoding = Encoding.GetEncoding("Windows-1252");

I downloaded the master branch, in which this was fixed according to issue history. However, I did not get it working correctly. But if I did this it worked just fine:

1. Add nuget packet System.Text.Encoding.CodePages
2. Change the line above to:

public static readonly Encoding AnsiEncoding = CodePagesEncodingProvider.Instance.GetEncoding(1252);

If not issue or if I did misbehave close issue as you see fit :)

**Comment by thimens** [comment]
From this [link](https://github.com/dotnet/corefx/issues/7768), it's not an issue

**Comment by erdomke** [comment]
This is now clarified in the `Readme.md` to help future individuals.  Sorry for the slow response.
