### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by billpeace** [erdomke/RtfPipe#52]
Hello! Please, Help!
I'm trying to parse RTF file and get StackOverflowException.

using (TextReader sr = new StringReader(bodyRtf))
{
                                RtfPipe.RtfSource source = new RtfPipe.RtfSource(sr);
                                html = RtfPipe.Rtf.ToHtml(source);
                               
}

Example in attachment (please, rename "new 1.txt" ->"new 1.rtf" )

Thank you a lot!

[new 1.txt](https://github.com/erdomke/RtfPipe/files/5329921/new.1.txt)

**Comment by erdomke** [comment]
This should now be resolved after the latest release.
