### ISSUE TITLE
Background colour bleeds across entire paragraph

### ISSUE THREAD

**Issue by RobSwDev** [erdomke/RtfPipe#54]
If you have rtf which has text with 2 different background colours on the same line, the background colours in the html conversion are not correct. The initial colour "bleeds" into the entire paragraph. See expected vs actual below.

![image](https://user-images.githubusercontent.com/26545948/96579549-f3561500-12ce-11eb-8d62-607eec64bad3.png)

Rtf
`\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}}\n{\colortbl ;\red255\green0\blue0;\red0\green0\blue255;\red0\green255\blue0;}\n{\*\generator Riched20 10.0.18362}\viewkind4\uc1 \n\pard\qc\highlight1\f0\fs24 Red\highlight0  \highlight2 Blue\highlight0  \highlight3 Green\highlight0\par\n}\n`

Html
`<div style="font-size:12pt;font-family:&quot;Microsoft Sans Serif&quot;;"><p style="text-align:center;background:#FF0000;margin:0;">Red<span style="background:#FFFFFF;"> </span><span style="background:#0000FF;">Blue</span><span style="background:#FFFFFF;"> </span><span style="background:#00FF00;">Green</span></p></div>`

**Comment by erdomke** [comment]
This should now be resolved after the latest release.
