### ISSUE TITLE
Bookmarks not converting to Anchor Links

### ISSUE THREAD

**Issue by Tetragramm** [erdomke/RtfPipe#57]
An rtf file containing `{\*\bkmkstart\bkmkcolf0\bkmkcoll1 _yosnw6cvungd}{\*\bkmkend _yosnw6cvungd}` does not produce a corresponding `<a name="_yosnw6cvungd"> </a>` tag pair.

It appears to be [line 46-49 in FormatContext.cs](https://github.com/erdomke/RtfPipe/blob/98aee27248419fe647148ced6c296bafa7feb463/RtfPipe/Html/FormatContext.cs#L46), for which complete removal seems to work.  Unfortunately, I cannot properly test to see what other effects it might have.

This might bear upon issue #47 and issue #48, I note the presence of anchor links in the test case.

**Comment by erdomke** [comment]
This should now be resolved after the latest release.
