### ISSUE TITLE
Multi-line text with background colour renders incorrectly

### ISSUE THREAD

**Issue by RobSwDev** [erdomke/RtfPipe#59]
This rtf has multi-line text with background colour set.

```{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}}\n{\colortbl ;\red255\green255\blue0;}\n{\*\generator Riched20 10.0.18362}\viewkind4\uc1 \n\pard\highlight1\f0\fs17 Background\par\n2nd line\par\n\highlight0\par\n}\n}```

The html generated by RtfPipe 2.0 is as follows
```
<div style="font-size:12pt;font-family:&quot;Microsoft Sans Serif&quot;;">
	<p style="background:#FFFF00;font-size:8.5pt;margin:0;">Background</p>
	<p style="background:#FFFF00;font-size:8.5pt;margin:0;">2nd line</p>
	<p style="font-size:8.5pt;margin:0;"><br></p>
</div>

```
This does not render the same as the original rtf. See Rtf on the left, Html on the right, in the pic below:
![image](https://user-images.githubusercontent.com/26545948/100091883-24d17b80-2e4d-11eb-95a3-a1824f589363.png)

**Comment by RobSwDev** [comment]
Another example. This one is strange, as the Rtf displays differently in Winforms's RichTextBox control than in Word. But neither display the way the RtfPipe output does.

```{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Microsoft Sans Serif;}}\n{\colortbl ;\red255\green0\blue0;\red0\green0\blue255;\red0\green255\blue0;}\n{\*\generator Riched20 10.0.18362}\viewkind4\uc1 \n\pard\qc\highlight1\f0\fs24 Red Background\highlight0  \highlight2 Bl\par\nue\highlight0  \highlight3 Green\highlight0\par\n}\n```

RtfPipe generates

```
<div style="font-size:12pt;font-family:&quot;Microsoft Sans Serif&quot;;">
	<p style="text-align:center;background:#0000FF;margin:0;">
		<span style="background:#FF0000;">Red Background</span>
		<span style="background:#FFFFFF;"> </span>Bl-</p>
	<p style="text-align:center;margin:0;">
		<span style="background:#0000FF;">ue</span>
		<span style="background:#00FF00;">Green</span>
	</p>
</div>
```
This shows the same background colour bleed as in #54 
![image](https://user-images.githubusercontent.com/26545948/100093815-f30de400-2e4f-11eb-866a-efc5764f4ee8.png)

**Comment by jespersh** [comment]
Appears to be caused by this line:
https://github.com/erdomke/RtfPipe/blob/2aedbf288eb012e2993330d334cf1a27f2026f7e/RtfPipe/Model/Builder.cs#L429

I am unsure what its purpose is
