### ISSUE TITLE
Encoding problem (crash in test)

### ISSUE THREAD

**Issue by martinrotter** [erdomke/RtfPipe#6]
I get exception in RtfParser.cs, line 173 `codePageStack.Push( encoding == null ? 0 : _encodings[encoding.WebName] );`

Exception says: 		Message	"Daný klíč není ve slovníku k dispozici."	string (Value with given key is not in dictionary.)

Value of encoding.WebName is `encoding.WebName = "Windows-1252"`, but values in dictionary have lowercase keys! You should make the dictionary key case INsensitive.

**Comment by martinrotter** [comment]
Same error in UpdateEncoding method.

**Comment by erdomke** [comment]
In the latest commit, the dictionary was made case insensitive.  A new NuGet package will be released shortly.
