### ISSUE TITLE
Bug in RTF Parser results in truncated HTML output. 

### ISSUE THREAD

**Issue by cfhirsch** [erdomke/RtfPipe#61]
I originally filed an issue in MsgReader, which uses RTFPipe:

https://github.com/Sicos1977/MSGReader/issues/250

HTML output ends up being truncated do to what looks like an error in RTFPipe.

Please see above link for details. I will also reach out via email and can provide a sample .msg file for a repro.

**Comment by erdomke** [comment]
This should be resolved in version 2.0.7677.4303.

**Comment by Sicos1977** [comment]
I just released a new MSGReader nuget package that has the latest RTFPipe version that fixes your problem.

https://www.nuget.org/packages/MSGReader/3.11.0
