### ISSUE TITLE
Issue with Non-Breaking Spaces - removes color

### ISSUE THREAD

**Issue by szczerbi** [erdomke/RtfPipe#7]
Rtf to decode: 
`{\\rtf1\\ansicpg1252\r\n{\r\n\\fonttbl\r\n{\\f0 Times New Roman;}\r\n{\\f1 Calibri;}\r\n}\r\n{\r\n\\colortbl\r\n;\r\n\\red0\\green0\\blue255;\r\n\\red0\\green0\\blue0;\r\n}\r\n\\nouicompat\\splytwnine\\htmautsp{\\pard\\plain\\ql{\\f1\\fs24\\cf2 <p><span style=\"color:#404040;font-family:calibri;font-size:12pt;\">On d&#233;termine la couverture de votre objectif de revenu d&#8217;invalidit&#233; en analysant dans quelle mesure vos rentr&#233;es de fonds couvrent vos sorties de fonds dans l'&#233;ventualit&#233; d&#8217;une invalidit&#233;. La couverture actuelle de votre objectif est de </span><strong><span style=\"color:#3265a4;font-family:calibri;font-size:12pt;\">79 %</span></strong><span style=\"color:#404040;font-family:calibri;font-size:12pt;\">. Votre besoin en revenu d'invalidit&#233; est de </span><strong><span style=\"color:#3265a4;font-family:calibri;font-size:12pt;\">3\\~320\\~853 $</span></strong><span style=\"color:#404040;font-family:calibri;font-size:12pt;\"> au cours de la p&#233;riode d'invalidit&#233; projet&#233;e de </span><strong><span style=\"color:#3265a4;font-family:calibri;font-size:12pt;\">192</span></strong><span style=\"color:#404040;font-family:calibri;font-size:12pt;\"> mois. Ce besoin inclut toutes les d&#233;penses mensuelles n&#233;cessaires comme la nourriture, les v&#234;tements et le logement. French blah.</span></p>}\\fs24\\par}\r\n}\r\n`

Html returned by RtfPipe.Rtf.ToHtml(...):
`<!DOCTYPE html ><html><head><meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" /></head><body><p><span style=\"font-family:Calibri;font-size:12pt\"><p><span style=\"color:#404040;font-family:calibri;font-size:12pt;\">On d&amp;#233;termine la couverture de votre objectif de revenu d&amp;#8217;invalidit&amp;#233; en analysant dans quelle mesure vos rentr&amp;#233;es de fonds couvrent vos sorties de fonds dans l'&amp;#233;ventualit&amp;#233; d&amp;#8217;une invalidit&amp;#233;. La couverture actuelle de votre objectif est de </span><strong><span style=\"color:#3265a4;font-family:calibri;font-size:12pt;\">79 %</span></strong><span style=\"color:#404040;font-family:calibri;font-size:12pt;\">. Votre besoin en revenu d'invalidit&amp;#233; est de </span><strong><span style=\"color:#3265a4;font-family:calibri;font-size:12pt;\">3</span>&nbsp;<span style=\"font-family:Calibri;font-size:12pt\">320</span>&nbsp;<span style=\"font-family:Calibri;font-size:12pt\">853 $</span></strong><span style=\"color:#404040;font-family:calibri;font-size:12pt;\"> au cours de la p&amp;#233;riode d'invalidit&amp;#233; projet&amp;#233;e de </span><strong><span style=\"color:#3265a4;font-family:calibri;font-size:12pt;\">192</span></strong><span style=\"color:#404040;font-family:calibri;font-size:12pt;\"> mois. Ce besoin inclut toutes les d&amp;#233;penses mensuelles n&amp;#233;cessaires comme la nourriture, les v&amp;#234;tements et le logement. French blah.</span></p></span></p></body></html>`

in the above example, the non-breaking spaces are put into separate spans, and the color is not carried through. so in the output, when "3 320 853 $" is supposed to be blue, only the first 3 is blue and the rest is black. help!

**Comment by erdomke** [comment]
This should be fixed now in the latest release.
